BasicTemplateMain/urls.py
import os
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from .admin import superadmin


urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    # Main Admin URL
    path('admin/', admin.site.urls),
    path('superadmin/', superadmin.urls),
    # Website URLs
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),  
    path('products/', include('products.urls')),  
    path('bag/', include('bag.urls')),  
    path('checkout/', include('checkout.urls')),  
    path('profile/', include('profiles.urls')),  
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bag/urls.py
from django.contrib import admin
from django.urls import path
from . import views


urlpatterns = [
    path('', views.view_bag, name='view_bag'),
    path('add/<item_id>/', views.add_to_bag, name='add_to_bag'),
    path('adjust/<item_id>/', views.adjust_bag, name='adjust_bag'),
    path('remove/<item_id>/', views.remove_from_bag, name='remove_from_bag'),
]

products/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.all_products, name='products'),
    path('<int:product_id>/', views.product_detail, name='product_detail'),
    path('add/', views.add_product, name='add_product'),
    path('edit/<int:product_id>/', views.edit_product, name='edit_product'),
    path('delete/<int:product_id>/', views.delete_product, name='delete_product'),
]

checkout/models.py
import uuid
from django.db import models
from django.db.models import Sum
from django.conf import settings
from django_countries.fields import CountryField
from products.models import Product
from profiles.models import UserProfile



class Order(models.Model):
    order_number = models.CharField(max_length=32, null=False, editable=False)
    user_profile = models.ForeignKey(UserProfile, on_delete=models.SET_NULL,
                                     null=True, blank=True, related_name='orders')
    full_name = models.CharField(max_length=50, null=False, blank=False)
    email = models.EmailField(max_length=254, null=False, blank=False)
    phone_number = models.CharField(max_length=20, null=False, blank=False)
    country = CountryField(blank_label='Country *',
                           max_length=40, null=False, blank=False)
    postcode = models.CharField(max_length=20, null=True, blank=True)
    town_or_city = models.CharField(max_length=40, null=False, blank=False)
    street_address1 = models.CharField(max_length=80, null=False, blank=False)
    street_address2 = models.CharField(max_length=80, null=True, blank=True)
    county = models.CharField(max_length=80, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    delivery_cost = models.DecimalField(
        max_digits=6, decimal_places=2, null=False, default=0)
    order_total = models.DecimalField(
        max_digits=10, decimal_places=2, null=False, default=0)
    grand_total = models.DecimalField(
        max_digits=10, decimal_places=2, null=False, default=0)
    original_bag = models.TextField(null=False, blank=False, default='')
    stripe_pid = models.CharField(
        max_length=254, null=False, blank=False, default='')
    
    
    def _generate_order_number(self):
        """
        Generates a random order number
        """
        return uuid.uuid4().hex.upper()
    
    def update_total(self):
        """
        Update grand total every time a line item is added,
        accounting for delivery costs
        """
        self.order_total = self.lineitems.aggregate(Sum('lineitem_total'))['lineitem_total__sum'] or 0
        if self.order_total < settings.FREE_DELIVERY_THRESHOLD:
            self.delivery_cost = self.order_total * settings.STANDARD_DELIVERY_PERCENTAGE / 100
        else:
            self.delivery_cost = 0
        self.grand_total = self.order_total + self.delivery_cost
        self.save()
    
    def save(self, *args, **kwargs):
        """
        Overides original save method to set the order number
        if it hasn't been set already
        """
        if not self.order_number:
            self.order_number = self._generate_order_number()
        super().save(*args, **kwargs)
        
    def __str__(self):
        return self.order_number
    
    
class OrderLineItem(models.Model):
    order = models.ForeignKey(Order, null=False, blank=False,
                              on_delete=models.CASCADE, related_name='lineitems')
    product = models.ForeignKey(
        Product, null=False, blank=False, on_delete=models.CASCADE)
    product_size = models.CharField(
        max_length=2, null=True, blank=True)  # XS, S, M, L, XL
    quantity = models.IntegerField(null=False, blank=False, default=0)
    lineitem_total = models.DecimalField(
        max_digits=6, decimal_places=2, null=False, blank=False, editable=False)
    
    
    def save(self, *args, **kwargs):
        """
        Overides original save method to set the order number
        if it hasn't been set already
        """
        self.lineitem_total = self.product.price * self.quantity
        super().save(*args, **kwargs)
        
    def __str__(self):
        return f'SKU {self.product.sku} on order {self.order.order_number}'

    

products/models.py
from django.db import models
from django import forms


class Category(models.Model):
    
    class Meta:
        verbose_name = 'Categories'
    
    name = models.CharField(max_length=254)
    friendly_name = models.CharField(max_length=254, blank=False, null=False)
    
    def __str__(self):
        return self.name
    
    def get_friendly_name(self):
        return self.friendly_name
        
class Product(models.Model):
    category = models.ForeignKey('Category', null=True, blank=True, on_delete=models.SET_NULL)
    sku = models.CharField(max_length=254, null=True, blank=True)
    name = models.CharField(max_length=254)
    description = models.TextField()
    has_sizes = models.BooleanField(default=False, null=True, blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    rating = models.DecimalField(
        max_digits=6, decimal_places=2, null=True, blank=True)
    image_url = models.URLField(max_length=1024, blank=True, null=True)
    image = models.ImageField(null=True, blank=True)
    
    def __str__(self):
        return self.name
    
    
    

products/forms.py
from django import forms
from .widgets import CustomClearableFileInput
from .models import Product, Category


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = '__all__'

    image = forms.ImageField(label='Image', required=False, widget=CustomClearableFileInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        categories = Category.objects.all()
        friendly_names = [(c.id, c.get_friendly_name()) for c in categories]

        self.fields['category'].choices = friendly_names
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'border-black rounded-0'

products/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Q
from django.db.models.functions import Lower
from .models import Product, Category
from .forms import ProductForm



def all_products(request):
    """Shows and displays all products."""
    products = Product.objects.all()
    query = None
    categories = None
    sort = None
    direction = None
    
    if request.GET:
        
        # Handles sorting by price, rating etc...
        if 'sort' in request.GET:
            sortkey = request.GET['sort']
            sort = sortkey
            if sortkey == 'name':
                sortkey = 'lower_name'
                products = products.annotate(lower_name=Lower('name'))
            if sortkey == 'category':
                sortkey = 'category__name'
            if 'direction' in request.GET:
                direction = request.GET['direction']
                if direction == 'desc':
                    sortkey = f'-{sortkey}'
            products = products.order_by(sortkey)
                
        # Handles categories        
        if 'category' in request.GET:
            categories = request.GET['category'].split(',')
            products = products.filter(category__name__in=categories)
            categories = Category.objects.filter(name__in=categories)
        
        # Handles Searches
        if 'q' in request.GET:
            query = request.GET['q']
            if not query:
                messages.error(request, 'Please enter a search query!')
                return redirect(reverse('products'))
            
            queries = Q(name__icontains=query) | Q(description__icontains=query)
            products = products.filter(queries)
            
    
    current_sorting = f'{sort}_{direction}'
    
    product_context = {
        'products' : products,
        'search_term' : query,
        'current_categories' : categories,
        'current_sorting' : current_sorting,
    }
    
    return render(request, 'products/products.html', product_context)

def product_detail(request, product_id):
    """Displays individual products."""
    product = get_object_or_404(Product, pk=product_id)
    
    product_context = {
        'product' : product,
    }
    
    return render(request, 'products/product_detail.html', product_context)

@login_required
def add_product(request):
    """To quickly add a product to the store"""
    if not request.user.is_superuser:
        messages.error(request, 'Nope! Only the store owner can do that')
        return redirect(reverse('home'))
    
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save()
            messages.success(request, 'Successfully added product!')
            return redirect(reverse('product_detail', args=[product.id]))
        else:
            messages.error(request, 'Failed to add product! Please check all details and try again.')
    else:
        form = ProductForm()
    
    form = ProductForm()
    template = 'products/add_product.html'
    context = {
        'form' : form,
    }
    
    return render(request, template, context)

@login_required      
def edit_product(request, product_id):
    """Edit product in store"""
    if not request.user.is_superuser:
        messages.error(request, 'Nope! Only the store owner can do that')
        return redirect(reverse('home'))
    
    product = get_object_or_404(Product, pk=product_id)
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            messages.success(request, 'Successfully updated product')
            return redirect(reverse('product_detail', args=[product.id]))
        else:
            messages.error(request, 'Failed to update product, please check all details and try again.')
    else:
        form = ProductForm(instance=product)
        messages.info(request, f'You are editing {product.name}')
    
    template = 'products/edit_product.html'
    context = {
        'form' : form,
        'product' : product,
    }
    
    return render(request, template, context)   

@login_required    
def delete_product(request, product_id):
    """ Delete store product """
    if not request.user.is_superuser:
        messages.error(request, 'Nope! Only the store owner can do that.')
        return redirect(reverse('home'))

    product = get_object_or_404(Product, pk=product_id)
    product.delete()
    messages.success(request, 'Product Deleted')
    return redirect(reverse('products'))

products/templates/products/add_product.html
{% extends "base.html" %}
{% load static %}


{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}
{% for y in global_styles  %}
<div class="{% if y.do_not_display %}
do-not-display {% else %} overlay {% endif %}" style="background-color: {{ y.base_background_color }} !important;">
</div>
<div class="container mt-5">
    <div class="row">
        <div class="{% if y.do_not_display %}
        do-not-display {% else %} col-12 col-md-6 {% endif %}" style="color: {{ y.base_font_color }} !important;">
            <hr>
            <h2 class="logo-font mb-4">
                Product Management
            </h2>
            <h5 class="">Add a Product</h5>
            <hr>
        </div>
    </div>

    <div class="row">
        <div class="{% if y.do_not_display %}
        do-not-display {% else %} col-12 col-md-6 {% endif %}" style="color: {{ y.base_font_color }} !important;">
            <form method="POST" action="{% url 'add_product' %}" class="form mb-2" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                {% if field.name != 'image' %}
                {{ field | as_crispy_field }}
                {% else %}
                {{ field }}
                {% endif %}
                {% endfor %}
                <div class="text-right">
                    <a class="{% if y.do_not_display %}
                    do-not-display
                    {% else %}
                    btn btn-outline-black mr-2 rounded-0
                    {% endif %}" style="background-color: {{ y.primary_button_base_color }} !important;
                        color: {{ y.primary_button_text_color }} !important;" href="{% url 'products' %}">Cancel
                    </a>
                    <button class="{% if y.do_not_display %}
                    do-not-display
                    {% else %} btn btn-black rounded-0 {% endif %}" style="background-color: {{ y.secondary_button_base_color }} !important;
                    color: {{ y.secondary_button_text_color }} !important;" type="submit">Add Product</button>
                </div>
            </form>
        </div>

    </div>
    {% endfor global_styles %}

</div>

{% endblock %}

{% block postloadjs %}
{{ block.super }}

<script type="text/javascript">
    $('#new-image').change(function () {
        var file = $('#new-image')[0].files[0];
        $('#filename').text(`Image will be set to: ${file.name}`);
    })
</script>

{% endblock %}

products/templates/products/edit_product.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="overlay"></div>
<div class="container">
    <div class="row">
        <div class="col-12 col-md-6">
            <hr>
            <h2 class="logo-font mb-4">Product Management</h2>
            <h5 class="text-muted">Edit a Product</h5>
            <hr>
        </div>
    </div>

    <div class="row">
        <div class="col-12 col-md-6">
            <form method="POST" action="{% url 'edit_product' product.id %}" class="form mb-2"
                enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                {% if field.name != 'image' %}
                {{ field | as_crispy_field }}
                {% else %}
                {{ field }}
                {% endif %}
                {% endfor %}
                <div class="text-right">
                    <a class="btn btn-outline-black rounded-0" href="{% url 'products' %}">Cancel</a>
                    <button class="btn btn-black rounded-0" type="submit">Update Product</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block postloadjs %}
{{ block.super }}

<script type="text/javascript">
    $('#new-image').change(function() {
             var file = $('#new-image')[0].files[0];
             $('#filename').text(`Image will be set to: ${file.name}`);
         })
    </script>

{% endblock %}

products/templates/products/product_detail.html
{% extends 'base.html' %}
{% load static %}


{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock page_header %}



{% block content %}
{% for y in global_styles  %}
<div class="{% if y.do_not_display %}
do-not-display {% else %} overlay {% endif %}" style="background-color: {{ y.base_background_color }} !important;">
</div>
{% endfor global_styles %}

<div class="container-fluid">
    <div class="row">
        <div class="col-12 col-md-6 col-lg-4 offset-lg-2">
            <div class="image-container my-5">
                {% if product.image %}
                <a href="{{ product.image.url }}" target="_blank">
                    <img class="card-img-top img-fluid" src="{{ product.image.url }}" alt="{{ product.name }}">
                </a>
                {% else %}
                <a href="">
                    <img class="card-img-top img-fluid" src="{{ MEDIA_URL }}noimage.png" alt="{{ product.name }}">
                </a>
                {% endif %}
            </div>
        </div>
        <div class="col-12 col-md-6 col-lg-4">
            <div class="products detail-container mb-5 mt-md-5">

                {% for y in global_styles %}
                <p class="{% if y.do_not_display %}
                do-not-display {% else %} mb-0 {% endif %}" style="color: {{ y.base_font_color }};">
                    {{ product.name }}
                </p>
                <p class="{% if y.do_not_display %}
                do-not-display {% else %} lead mb-0 text-left font-weight-bold {% endif %}"
                    style="color: {{ y.base_font_color }};">
                    £{{ product.price }}
                </p>
                {% endfor global_styles %}
                {% if product.category %}
                {% for y in global_styles %}
                <p class="{% if y.do_not_display %}
            do-not-display {% else %} small mt-1 mb-0 {% endif %}">
                    <a class="text-muted" href="{% url 'products' %}?category={{ product.category.name }}"
                        style="color: {{ y.base_font_color }} !important;">
                        <i class="{% if y.do_not_display %}
                        do-not-display {% else %} fas fa-tag mr-1 {% endif %}" style="color: {{ y.all_icon_colors }};">
                        </i>
                        {{ product.category.friendly_name }}
                    </a>
                </p>
                {% endfor global_styles %}
                {% endif %}

                {% if product.rating %}
                {% for y in global_styles %}
                <small class="{% if y.do_not_display %}
                do-not-display {% else %} test-muted {% endif %}" style="color: {{ y.base_font_color }} !important;">
                    <i class="{% if y.do_not_display %}
                    do-not-display {% else %} fa fa-star mr-1 {% endif %}" style="color: {{ y.all_icon_colors }};">
                    </i>
                    {{ product.rating }} / 5
                </small>
                {% endfor global_styles %}
                {% else %}
                <small class="test-muted">NO RATING</small>
                {% endif %}
                {% if request.user.is_superuser %}
                <small class="ml-3">
                    <a href="{% url 'edit_product' product.id %}">Edit</a> |
                    <a class="text-danger" href="{% url 'delete_product' product.id %}">Delete</a>
                </small>
                {% endif %}
                {% for y in global_styles %}
                <p class="{% if y.do_not_display %}
                do-not-display {% else %} mt-3 {% endif %}" style="color: {{ y.base_font_color }};">
                    {{ product.description }}
                </p>
                {% endfor global_styles %}
                <form class="form" action="{% url 'add_to_bag' product.id %}" method="POST">
                    {% csrf_token %}
                    <div class="form-row">
                        {% with product.has_sizes as s  %}
                        {% if s %}
                        <div class="col-12">
                            <p><strong>Size:</strong></p>
                            <select class="form-control rounded-0 w-50" name="product_size" id="id_product_size">
                                <option value="xs">XS</option>
                                <option value="s">S</option>
                                <option value="m" selected>M</option>
                                <option value="l">L</option>
                                <option value="xl">XL</option>
                            </select>
                        </div>

                        {% endif %}

                        <div class="col-12">
                            {% for x in products_page_customisation %}
                            <p class="{% if x.do_not_display %}
                            do-not-display {% else %} mt-3 {% endif %}"
                                style="color: {{ x.products_page_text_color }};">
                                <strong>Quantity:</strong>
                            </p>
                            {% endfor %}
                            <div class="form-group w-50">
                                <div class="input-group">
                                    {% for x in products_page_customisation %}
                                    <div class="input-group-prepend">
                                        <button class="{% if x.do_not_display %}
                                        do-not-display {% else %} decrement-qty btn btn-black rounded-0 {% endif %}"
                                            style="background-color: {{ x.product_quantity_buttons }} !important;"
                                            data-item_id="{{ product.id }}" id="decrement-qty_{{ product.id }}">
                                            <span class="icon">
                                                <i class="fas fa-minus"></i>
                                            </span>
                                        </button>
                                    </div>
                                    {% endfor %}

                                    <input class="form-control qty_input" type="number" name="quantity" value="1"
                                        min="1" max="99" data-item_id="{{ product.id }}" id="id_qty_{{ product.id }}">
                                    <div class="input-group-append">

                                        {% for x in products_page_customisation %}
                                        <div class="{% if x.do_not_display %}
                                        do-not-display {% else %} increment-qty btn btn-black rounded-0 {% endif %}"
                                            style="background-color: {{ x.product_quantity_buttons }} !important;"
                                            data-item_id="{{ product.id }}" id="increment-qty_{{ product.id }}">
                                            <span class="icon">
                                                <i class="fas fa-plus"></i>
                                            </span>
                                        </div>
                                        {% endfor %}

                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col{% if s %}-12 mt-2 {% endif %}">
                            {% for y in global_styles %}
                            <a href="{% url 'products' %}" class="{% if y.do_not_display %}
                            do-not-display {% else %} btn btn-outline-black rounded-0 mt-5 {% endif %}"
                                style="background-color: {{ y.primary_button_base_color }};">
                                <span class="icon">
                                    <i class="{% if y.do_not_display %}
                                    do-not-display {% else %} fas fa-chevron-left {% endif %}"
                                        style="color: {{ y.primary_button_text_color }};"></i>
                                </span>
                                <span class="{% if y.do_not_display %}
                                do-not-display {% else %} text-uppercase {% endif %}"
                                    style="color: {{ y.primary_button_text_color }};">Keep Shopping</span>
                            </a>
                            <input type="submit" class="{% if y.do_not_display %}
                            do-not-display {% else %} btn btn-black rounded-0 text-uppercase mt-5 {% endif %}"
                                style="background-color: {{ y.secondary_button_base_color }} !important; color: {{ y.secondary_button_text_color }}"
                                value="Add to Bag">
                            {% endfor global_styles %}
                        </div>
                        <input type="hidden" name="redirect_url" value="{{ request.path }}">
                        {% endwith %}

                    </div>
                </form>
            </div>
        </div>
    </div>

</div>
{% endblock content %}


{% block postloadjs %}
{{ block.super }}
{% include 'products/includes/quantity_input_script.html' %}
{% endblock postloadjs %}